# テスト用
spring:
  messages:
    basename: messages, i18n/messages
    cache-duration: -1
    encoding: UTF-8
  batch:
    initialize-schema: always
  flyway:
    locations: classpath:db/migration, classpath:db/data
  h2:
    console:
      settings:
        web-allow-others: false
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:algolearn;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: 
    password: 
    driverClassName: org.h2.Driver
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    platform: test

ap:
  question:
    imagefilepath: file:/F://AP_AM

server:
  charactercode: SJIS
